workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-8
    acceleratorType: NVIDIA_TESLA_T4
    acceleratorCount: 1
  pythonPackageSpec:
    executorImageUri: us-docker.pkg.dev/vertex-ai/training/pytorch-gpu.1-9:latest
    packageUris:
      - gs://my-bucket/noise-distillation-trainer/python_package/noise-distillation-trainer-0.1.tar.gz
    pythonModule: NoiseDistillation.ConvTasNet.NoiseDistillation
    args:
      - --job-dir=gs://my-bucket/noise-distillation-trainer/model
      - --model-name=finetuned-bert-classifier
    env:
    - name: AWS_ACCESS_KEY_ID
      value: "REDACTED"
    - name: AWS_SECRET_ACCESS_KEY
      value: "REDACTED"

  replicaCount: 1
